services:
  authenticated-todo-app:
    build: .
    ports:
      - "64000:64000"
    env_file: .env.docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword1234"
      MYSQL_DATABASE: authenticated_todos
      MYSQL_USER: auth_todos
      MYSQL_PASSWORD: password1234
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  app-network: